-- Users Table
-- This table stores user information, linking to Supabase's auth.users table.
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Locations Table
-- Stores geographic coordinates selected by users.
CREATE TABLE IF NOT EXISTS public.locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Orders Table
-- This table tracks all laundry orders placed by customers.
CREATE TABLE IF NOT EXISTS public.orders (
    id VARCHAR(255) PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    contact_number VARCHAR(50) NOT NULL,
    loads INTEGER NOT NULL,
    weight_kg NUMERIC(10, 2) NOT NULL,
    total_price NUMERIC(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row-Level Security (RLS) for all tables
-- This is a critical security measure for Supabase.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Define who can access or modify the data.

-- Profiles are visible to the owner.
CREATE POLICY "Users can view their own profile."
ON public.profiles FOR SELECT
USING ( auth.uid() = id );

-- Users can insert their own profile.
CREATE POLICY "Users can insert their own profile."
ON public.profiles FOR INSERT
WITH CHECK ( auth.uid() = id );

-- Locations are visible to the owner.
CREATE POLICY "Users can view their own locations."
ON public.locations FOR SELECT
USING ( auth.uid() = user_id );

-- Users can insert their own locations.
CREATE POLICY "Users can insert their own locations."
ON public.locations FOR INSERT
WITH CHECK ( auth.uid() = user_id );

-- All users can view all orders (for admin and customer views)
-- You might want to restrict this further in a real application.
CREATE POLICY "Allow all users to read orders."
ON public.orders FOR SELECT
USING ( true );

-- All users can create orders
CREATE POLICY "Allow all users to create orders."
ON public.orders FOR INSERT
WITH CHECK ( true );
